### ISSUE TITLE
Как сгенерировать сайт

### ISSUE THREAD

**Issue by norvegec** [taksebeperevod/game-programming-patterns#11]
До этого не имел дела с Python и его модулями. Пользуюсь виндой, скрипт из этого репозитория ветки Russian заработал только на  версии 2.7.8 с офф сайта. Когда я начал переводить, билд падал - где-то внутри использовался asci coder вметсо utf-8. В "соседнем" репозиории Олега лежит `format.py`, который у меня "завелся".

**Comment by marapper** [comment]
А зачем пока генерировать сайт? Сейчас пока достаточно маркдауна.

format.py, да, надо будет, но это надо согласовывать с автором. Пока надо стараться, чтобы мерж потом прошел максимально чисто.
