### ISSUE TITLE
Merge оригинала, перевода на notabenoid и этого репозиория

### ISSUE THREAD

**Issue by norvegec** [taksebeperevod/game-programming-patterns#12]
Как вы видите процесс переноса?
Мои мысли по этому поводу:
1. Фиксируемcя текст на текущий момент в этом репозитории.
2. Находим абзацы-Diff'ы между ним и `notabenoid`
3. На `notabenoid` исходный текс приводим в соответсвие с этим репо-ием, перевод измененных фраз убираем.
4.1. Допереводим оставшиеся главы.
4.2. Сергей выдает права на оценку перевода только редакторам (что будет с текущими оценками?) Редакторы оценивают уже переведенные главы.
5. Собираем перевод с максим. оценками.
6. Обновляем скрипт и перевод глав.
7. Комитим отдельными markdown'ами
8. Комитим комментарии примеров.

**Comment by IngaJolly** [comment]
На notebenoid мы как бы уже забили вместе с его переводами (можно опираться на них, вроде как). Обратись к Сергею, он там инструкции составляет. Вот одна из них.
https://github.com/taksebeperevod/game-programming-patterns/pull/2/files

**Comment by marapper** [comment]
В Процесс уже все, в принципе, описано, надо только дорабатывать детали.

Сейчас один из редакторов выбирает главу, сводит ее вместе и выкладывает в виде пулл-реквеста, который мы обсуждаем, предлагаем варианты и т.д. Когда все готово, главный редактор все соберет. Пока предполагается, что это буду я :), но все обсуждаемо. К тому же, окончательный редакторский перевод я предлагаю в любом случае отдать на вычитку сообщества + я приглашу пару людей из айти- и игровой индустрии на ревью.

При переводе можно опираться на нотабеноид, но не факт, что на максимальные оценки - во-первых, оценок та почти нет, во-вторых, главное на этом этапе - связность текста, его однозначное соответствие английскому (практически дословность, за исключением метафор, принципов построения предложений и более удачных формулировок). Если текст после перевода все еще выглядит "английским", не беда - это будет правиться во второй проход при редактуре. Но, конечно, плюс, если такие места будут решены сразу.

Про форматирование текста я дополню описание процесса - писал вчера Инге. Пулл содержит маркдаун+текст.

Да, понадобятся имена (реальные или какие хотите видеть) участников и имейлы (с указанием, можно ли будет их оставить на странице с благодарностями). То же самое, кстати, о использовании переводов с нотабеноида - я бы попросил, если в процессе работы над главой используются переводы с нотабеноида, указывать потом в описании к пулл-реквесту, ники авторов использованных предложений. С ними будем разбираться чуть позже (в принципе, всех задействованных я уже уведомлял).
