### ISSUE TITLE
Закрытие notabenoid

### ISSUE THREAD

**Issue by GromHoll** [taksebeperevod/game-programming-patterns#16]
**notabenoid.com** закрывают из-за проблем с правообладателями.
Сейчас дают время, что бы основатели переводов скачали их.
@marapper можешь сделать это и выложить в публичный доступ, да бы не потерять наработки.

**Comment by IngaJolly** [comment]
А куда он делся то, вообще? Давай на пару допереводим, что ли. Но у меня пока на работе тоже запарка. Если он не выкачает, то ты выкачай.  И прямо сюда добавь. Всего один день есть на скачку.

**Comment by GromHoll** [comment]
@IngaJolly 
Попробую.
Там, правда, говорится, что выкачать могут _владельцы_.
Если у меня завтра не получится - попробую с администрацией поговорить.

В любом случае - завтра до обеда отпишусь.

**Comment by GromHoll** [comment]
Пока возможности скачать нет ни у кого (судя по обсуждению в блоге разработчика), будем ждать.

**Comment by marapper** [comment]
Да, я жду, когда Ромахин даст возможность скачать оригиналы / готовое. Прикреплю здесь.

**Comment by GromHoll** [comment]
@marapper 
Отлично!

**Comment by GromHoll** [comment]
Появилась возможность скачать перевод. Архив ниже.
[ссылка с переводами](https://drive.google.com/file/d/0B3y1xFbgUkjmdWhSZHNDZVNCZkU/view?usp=sharing)

**Comment by marapper** [comment]
Я, собственно, уже скачал. Удобнее всего добавить прямо пулл-реквестом https://github.com/taksebeperevod/game-programming-patterns/pull/18
